---
- hosts: all
  become: yes
  
  pre_tasks:
    - name: apt-get update
      become: yes
      apt:
        update_cache: yes

    - name: update all packages to the latest version
      apt:
        upgrade: dist
        
 

  vars:
    swap_file_size_mb: '6024'
  
  roles:
    # Preserve the apt cache
    - role: gantsign.apt
      apt_preserve_cache: yes

    - role: geerlingguy.java
      become: yes
    
    - { role: geerlingguy.git }

    - role: geerlingguy.nodejs
      nodejs_npm_global_packages:
        - name: grunt-cli
        - name: grunt-init
        - name: gulp-cli
        - name: npm-check-updates
        - name: typescript
        - name: ts-node
        - name: typings
        - name: json-server
        - name: "@vue/cli"
        
    - role: geerlingguy.docker
      docker_users:
        - vagrant

    - role: geerlingguy.swap

    # Install Go language SDK
    - role: gantsign.golang
      golang_gopath: '$HOME/workspace-go'


    #- role: Comcast.sdkman