---
- hosts: all

  pre_tasks:
    - name: apt-get update
      become: yes
      apt:
        update_cache: yes

    - name: update all packages to the latest version
      apt:
        upgrade: dist
        
  become: yes


  
  roles:
    # Preserve the apt cache
    - role: gantsign.apt
      apt_preserve_cache: yes

    - role: geerlingguy.java
      become: yes
    
    - { role: geerlingguy.git }

    - role: geerlingguy.nodejs

    - role: geerlingguy.docker

    #- role: Comcast.sdkman