---
- src: gantsign.apt
  #version: 'v3.8.1'
- src: geerlingguy.java
 # version: '3.0.0'
- src: geerlingguy.git
 # version: '1.5.0'
- src: geerlingguy.nodejs
  #version: '5.1.1'
- src: geerlingguy.docker
 # version: 'v1.0.42'
- src: geerlingguy.swap
 # version: '1.3.2'
